alistyleConfig/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from asosiyApp.views import HomeLoginsizView

urlpatterns = ([
                   path('admin/', admin.site.urls),
                   path('', HomeLoginsizView.as_view()),
                   path('asosiy/', include("asosiyApp.urls")),
                   path('buyurtma/', include("buyurtmaApp.urls")),
                   path('user/', include("userApp.urls")),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

userApp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('login/', LoginView.as_view()),
    path('logout/', LoginView.as_view()),
    path('register/', RegisterView.as_view()),
    path('tasdiqlash/', KodTasdiqlash.as_view()),
]

asosiyApp/models.py
from django.db import models

from userApp.models import Profil


class Bolim(models.Model):
    nom = models.CharField(max_length=255)
    rasm = models.FileField(upload_to="bolimlar")

    def __str__(self):
        return self.nom


class Mahsulot(models.Model):
    nom = models.CharField(max_length=255)
    brend = models.CharField(max_length=255)
    narx = models.PositiveIntegerField()
    chegirma = models.PositiveIntegerField(default=0)
    batafsil = models.TextField()
    kafolat = models.CharField(max_length=255)
    yetkazish = models.CharField(max_length=255)
    mavjud = models.BooleanField(default=True)
    davlat = models.CharField(max_length=255)
    bolim = models.ForeignKey(Bolim, on_delete=models.CASCADE)

    def __str__(self):
        return self.nom


class Media(models.Model):
    rasm = models.FileField()
    mahsulot = models.ForeignKey(Mahsulot, on_delete=models.CASCADE)


class Izoh(models.Model):
    profil = models.ForeignKey(Profil, on_delete=models.CASCADE)
    mahsulot = models.ForeignKey(Mahsulot, on_delete=models.CASCADE)
    matn = models.TextField()
    baho = models.PositiveIntegerField(default=5)
    sana = models.DateField()

templates/page-components.html
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>Website title - bootstrap html template</title>

<link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico">

<!-- jQuery -->
<script src="js/jquery-2.0.0.min.js" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="js/bootstrap.bundle.min.js" type="text/javascript"></script>
<link href="css/bootstrap.css" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="css/ui.css" rel="stylesheet" type="text/css"/>
<link href="css/responsive.css" rel="stylesheet" />

<!-- custom javascript -->
<script src="js/script.js" type="text/javascript"></script>

<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

}); 
// jquery end
</script>

</head>
<body>

<header class="section-header">
<section class="header-main border-bottom">
<div class="container">
	<a href="http://bootstrap-ecommerce.com" class="brand-wrap"><img class="logo" src="images/logo.png"></a>
</div> <!-- container.// -->
</section>
</header> <!-- section-header.// -->


<section class="section-content padding-y">
<div class="container">

<header class="section-heading">
	<h2 class="section-title">All components </h2>
</header><!-- sect-heading -->

<article>

<p>Please open the folder <i class="fa fa-folder text-warning"></i> /<strong><a target="_blank" href="_HTML-Components/">HTML-Components</a></strong> </p>
<p>Each component created in separated file</p>



</article>


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


</body>
</html>

templates/page-detail-product.html
{% extends 'header.html' %}

{% block content %}

<section class="py-3 bg-light">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Category name</a></li>
            <li class="breadcrumb-item"><a href="#">Sub category</a></li>
            <li class="breadcrumb-item active" aria-current="page">Items</li>
        </ol>
    </div>
</section>

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content bg-white padding-y">
    <div class="container">

        <!-- ============================ ITEM DETAIL ======================== -->
        <div class="row">
            <aside class="col-md-6">
                <div class="card">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                            <div><a href="#"><img src="{{ mahsulot.media_set.first.rasm.url }}"></a></div>
                        </div> <!-- slider-product.// -->
                        <div class="thumbs-wrap">
                            {% for media in mahsulot.media_set.all|slice:"1:6" %}
                            <a href="#" class="item-thumb"> <img src="{{ media.rasm.url }}"></a>
                            {% endfor %}
                        </div> <!-- slider-nav.// -->
                    </article> <!-- gallery-wrap .end// -->
                </div> <!-- card.// -->
            </aside>
            <main class="col-md-6">
                <article class="product-info-aside">

                    <h2 class="title mt-3">{{ mahsulot.nom }} </h2>

                    <div class="rating-wrap my-3">
                        <ul class="rating-stars">
                            <li style="width:{{ortachasi}}%" class="stars-active">
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </li>
                            <li>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </li>
                        </ul>
                        <small class="label-rating text-muted">{{mahsulot.izoh_set.count}} reviews</small>
                        <small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154 orders
                        </small>
                    </div> <!-- rating-wrap.// -->

                    <div class="mb-3">
                        <var class="price h4">SO'M {{ mahsulot.narx }}</var>
                        <span class="text-muted">{{ mahsulot.chegirma }}% chegirma</span>
                    </div> <!-- price-detail-wrap .// -->

                    <p>{{ mahsulot.batafsil }} </p>


                    <dl class="row">
                        <dt class="col-sm-3">Manufacturer</dt>
                        <dd class="col-sm-9"><a href="#">{{ mahsulot.brend }}</a></dd>

                        <dt class="col-sm-3">Article number</dt>
                        <dd class="col-sm-9">{{ mahsulot.id }}</dd>

                        <dt class="col-sm-3">Guarantee</dt>
                        <dd class="col-sm-9">{{ mahsulot.kafolat }}</dd>

                        <dt class="col-sm-3">Delivery time</dt>
                        <dd class="col-sm-9">{{ mahsulot.yetkazish }}</dd>

                        <dt class="col-sm-3">Do'konda</dt>
                        {% if mahsulot.mavjud %}
                        <dd class="col-sm-9">Mavjud</dd>
                        {% else %}
                        <dd class="col-sm-9">Mavjud emas</dd>
                        {% endif %}
                    </dl>

                    <div class="form-row  mt-4">
                        <div class="form-group col-md flex-grow-0">
                            <div class="input-group mb-3 input-spinner">
                                <div class="input-group-prepend">
                                    <button class="btn btn-light" type="button" id="button-plus"> +</button>
                                </div>
                                <input type="text" class="form-control" name="miqdor" value="{{item.id}}">
                                <div class="input-group-append">
                                    <button class="btn btn-light" type="button" id="button-minus"> &minus;</button>
                                </div>
                            </div>
                        </div> <!-- col.// -->
                        <div class="form-group col-md">
                            <a href="/buyurtma/add_savatitem/{{mahsulot.id}}/" class="btn  btn-primary">
                                <i class="fas fa-shopping-cart"></i> <span class="text">Add to cart</span>
                            </a>
                            <a href="#" class="btn btn-light">
                                <i class="fas fa-envelope"></i> <span class="text">Contact supplier</span>
                            </a>
                        </div> <!-- col.// -->
                    </div> <!-- row.// -->

                </article> <!-- product-info-aside .// -->
            </main> <!-- col.// -->
        </div> <!-- row.// -->

        <!-- ================ ITEM DETAIL END .// ================= -->


    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

<div class="container d-flex justify-content-center align-items-center">
    <form method="post"> {%csrf_token%}
        <div class="form-group">
            <label for="smileyRating">Your rating</label>
            <div class="rating-container d-flex" id="smileyRating" style="gap: 20px;">
                <input type="radio" name="rating" value="1" id="smiley1" style="display:none;" checked>
                <label class="smiley-face" for="smiley1" style="cursor: pointer">&#9785;</label>
                <input type="radio" name="rating" value="2" id="smiley2" style="display:none;" >
                <label class="smiley-face" for="smiley2" style="cursor: pointer">&#x1F610;</label>
                <input type="radio" name="rating" value="3" id="smiley3" style="display:none;" >
                <label class="smiley-face" for="smiley3" style="cursor: pointer">&#x1F642;</label>
                <input type="radio" name="rating" value="4" id="smiley4" style="display:none;" >
                <label class="smiley-face" for="smiley4" style="cursor: pointer">&#x1F600;</label>
                <input type="radio" name="rating" value="5" id="smiley5" style="display:none;" >
                <label class="smiley-face" for="smiley5" style="cursor: pointer">&#x1F929;</label>
            </div>
        </div>
        <div class="form-group">
            <label for="exampleInputComment1">Your comment</label>
            <input type="text" class="form-control" id="exampleInputComment1" aria-describedby="commentHelp"
                   placeholder="Enter your comment" name="comment">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <div id="selectedRating"></div>

    <script>
        document.addEventListener("DOMContentLoaded", () => {
            var smileyFaces = document.querySelectorAll('.smiley-face');

            smileyFaces.forEach((face) => {
              face.addEventListener('click', () => {
                // reset transform of all smiley faces
                smileyFaces.forEach((face) => {
                  face.style.transform = "none"; // add !important if necessary
                });
                // scale up the clicked smiley face
                face.style.transform = "scale(2)"; // add !important if necessary
              });
            });
          });
    </script>
</div>


<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="text-center mb-4">Reviews</h2>
            <hr>
            {% for izoh in mahsulot.izoh_set.all %}
            <div class="row">
                <div class="col-sm-2">
                    <div class="text-center">
                        {% if izoh.reyting == 1 %}
                        <span class="smiley-face">&#9785;</span>
                        {% elif izoh.reyting == 2 %}
                        <span class="smiley-face">&#x1F610;</span>
                        {% elif izoh.reyting == 3 %}
                        <span class="smiley-face">&#x1F642;</span>
                        {% elif izoh.reyting == 4 %}
                        <span class="smiley-face">&#x1F600;</span>
                        {% elif izoh.reyting == 5 %}
                        <span class="smiley-face">&#x1F929;</span>
                        {% endif %}
                    </div>
                </div>
                <div class="col-sm-10">
                    <p>{{ izoh.matn }}</p>
                    <div class="user d-flex" style="gap: 300px">
                        <p><small class="text-muted">{{ izoh.sana }}</small></p>
                        <p><small class="text-muted">{{ izoh.profil.first_name }} {{ izoh.profil.last_name }}</small></p>
                    </div>
                </div>
            </div>
            <hr>
            {% empty %}
            <p>No reviews yet.</p>
            {% endfor %}
        </div>
    </div>
</div>


<!-- ========================= SECTION SUBSCRIBE  ========================= -->
<section class="padding-y-lg bg-light border-top">
    <div class="container">

        <p class="pb-2 text-center">Delivering the latest product trends and industry news straight to your inbox</p>

        <div class="row justify-content-md-center">
            <div class="col-lg-4 col-sm-6">
                <form class="form-row">
                    <div class="col-8">
                        <input class="form-control" placeholder="Your Email" type="email">
                    </div> <!-- col.// -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-block btn-warning"><i class="fa fa-envelope"></i> Subscribe
                        </button>
                    </div> <!-- col.// -->
                </form>
                <small class="form-text">We’ll never share your email address with a third-party. </small>
            </div> <!-- col-md-6.// -->
        </div>


    </div>
</section>
<!-- ========================= SECTION SUBSCRIBE END// ========================= -->


<!-- ========================= FOOTER ========================= -->
<footer class="section-footer bg-secondary">
    <div class="container">
        <section class="footer-top padding-y-lg text-white">
            <div class="row">
                <aside class="col-md col-6">
                    <h6 class="title">Brands</h6>
                    <ul class="list-unstyled">
                        <li><a href="#">Adidas</a></li>
                        <li><a href="#">Puma</a></li>
                        <li><a href="#">Reebok</a></li>
                        <li><a href="#">Nike</a></li>
                    </ul>
                </aside>
                <aside class="col-md col-6">
                    <h6 class="title">Company</h6>
                    <ul class="list-unstyled">
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Career</a></li>
                        <li><a href="#">Find a store</a></li>
                        <li><a href="#">Rules and terms</a></li>
                        <li><a href="#">Sitemap</a></li>
                    </ul>
                </aside>
                <aside class="col-md col-6">
                    <h6 class="title">Help</h6>
                    <ul class="list-unstyled">
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">Money refund</a></li>
                        <li><a href="#">Order status</a></li>
                        <li><a href="#">Shipping info</a></li>
                        <li><a href="#">Open dispute</a></li>
                    </ul>
                </aside>
                <aside class="col-md col-6">
                    <h6 class="title">Account</h6>
                    <ul class="list-unstyled">
                        <li><a href="#"> User Login </a></li>
                        <li><a href="#"> User register </a></li>
                        <li><a href="#"> Account Setting </a></li>
                        <li><a href="#"> My Orders </a></li>
                    </ul>
                </aside>
                <aside class="col-md">
                    <h6 class="title">Social</h6>
                    <ul class="list-unstyled">
                        <li><a href="#"> <i class="fab fa-facebook"></i> Facebook </a></li>
                        <li><a href="#"> <i class="fab fa-twitter"></i> Twitter </a></li>
                        <li><a href="#"> <i class="fab fa-instagram"></i> Instagram </a></li>
                        <li><a href="#"> <i class="fab fa-youtube"></i> Youtube </a></li>
                    </ul>
                </aside>
            </div> <!-- row.// -->
        </section>  <!-- footer-top.// -->

        <section class="footer-bottom text-center">

            <p class="text-white">Privacy Policy - Terms of Use - User Information Legal Enquiry Guide</p>
            <p class="text-muted"> &copy 2019 Company name, All rights reserved </p>
            <br>
        </section>
    </div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

{% endblock %}

templates/page-profile-main.html
{% extends 'header.html' %}
{% block content %}

<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg-gray">
<div class="container">
	<h2 class="title-page">My account</h2>
</div> <!-- container //  -->
</section>
<!-- ========================= SECTION PAGETOP END// ========================= -->
	
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
<div class="container">

<div class="row">
	<aside class="col-md-3">
		<nav class="list-group">
			<a class="list-group-item active" href="page-profile-main.html"> Account overview  </a>
			<a class="list-group-item" href="page-profile-address.html"> My Address </a>
			<a class="list-group-item" href="page-profile-orders.html"> My Orders </a>
			<a class="list-group-item" href="page-profile-wishlist.html"> My wishlist </a>
			<a class="list-group-item" href="page-profile-seller.html"> My Selling Items </a>
			<a class="list-group-item" href="page-profile-setting.html"> Settings </a>
			<a class="list-group-item" href="page-index-1.html"> Log out </a>
		</nav>
	</aside> <!-- col.// -->
	<main class="col-md-9">

		<article class="card mb-3">
			<div class="card-body">
				<figure class="icontext">
						<div class="icon">
							<img class="rounded-circle img-sm border" src="{{profil.rasm.url}}">
						</div>
						<div class="text">
							<strong> {{profil.first_name}} {{profil.last_name}}</strong> <br>
							<p class="mb-2"> {{profil.email}}  </p>
							<a href="#" class="btn btn-light btn-sm">Edit</a>
						</div>
				</figure>
				<hr>
				<p>
					<i class="fa fa-map-marker text-muted"></i> &nbsp; My address:  
					 <br>
					{{profil.davlat}}, {{profil.shahar}}, {{profil.manzil}} &nbsp
					<a href="#" class="btn-link"> Edit</a>
				</p>


				<article class="card-group card-stat">

					<figure class="card bg">
						<div class="p-3">
							 <h4 class="title">{{buyurtmalar_soni}}</h4>
							<span>Orders</span>
						</div>
					</figure>

					<figure class="card bg">
						<div class="p-3">
							 <h4 class="title">{{tanlanganlar_soni}}</h4>
							<span>Wishlists</span>
						</div>
					</figure>
					<figure class="card bg">
						<div class="p-3">
							 <h4 class="title">12</h4>
							<span>Awaiting delivery</span>
						</div>
					</figure>
					<figure class="card bg">
						<div class="p-3">
							 <h4 class="title">50</h4>
							<span>Delivered items</span>
						</div>
					</figure>
				</article>
				

			</div> <!-- card-body .// -->
		</article> <!-- card.// -->

		<article class="card  mb-3">
			<div class="card-body">
				<h5 class="card-title mb-4">Recent orders </h5>	

					{% for buyurtma in buyurtmalar %}
				<div class="row">
					{% for item in buyurtma.savat.savatitem_set.all %}
				<div class="col-md-6">
					<figure class="itemside  mb-3">
						<div class="aside"><img src="{{item.mahsulot.media_set.first.rasm.url}}" class="border img-sm"></div>
						<figcaption class="info">
							<time class="text-muted"><i class="fa fa-calendar-alt"></i> {{buyurtma.sana}}</time>
							<p>{{item.mahsulot.nom}} </p>
							<span class="text-success">{{buyurtma.savat.holat}} </span>
						</figcaption>
					</figure>
				</div> <!-- col.// -->
				{% endfor %}
			</div> <!-- row.// -->
				{% endfor %}

			<a href="#" class="btn btn-outline-primary btn-block"> See all orders <i class="fa fa-chevron-down"></i>  </a>
			</div> <!-- card-body .// -->
		</article> <!-- card.// -->

	</main> <!-- col.// -->
</div>

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/page-profile-wishlist.html
{% extends 'header.html' %}
{% block content %}
<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg-gray">
    <div class="container">
        <h2 class="title-page">My account</h2>
    </div> <!-- container //  -->
</section>
<!-- ========================= SECTION PAGETOP END// ========================= -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">

        <div class="row">
            <aside class="col-md-3">
                <nav class="list-group">
                    <a class="list-group-item" href="page-profile-main.html"> Account overview </a>
                    <a class="list-group-item" href="page-profile-address.html"> My Address </a>
                    <a class="list-group-item" href="page-profile-orders.html"> My Orders </a>
                    <a class="list-group-item active" href="page-profile-wishlist.html"> My wishlist </a>
                    <a class="list-group-item" href="page-profile-seller.html"> My Selling Items </a>
                    <a class="list-group-item" href="page-profile-setting.html"> Settings </a>
                    <a class="list-group-item" href="page-index-1.html"> Log out </a>
                </nav>
            </aside> <!-- col.// -->
            <main class="col-md-9">

                <article class="card">
                    <div class="card-body">
                        {% for tanlangan in tanlanganlar %}
                        <div class="row">
                            <div class="col-md-6">
                                <figure class="itemside mb-4">
                                    <div class="aside"><img src="{{tanlangan.mahsulot.media_set.first.rasm.url}}"
                                                            class="border img-md"></div>
                                    <figcaption class="info">
                                        <a href="/asosiy/mahsulot/{{tanlangan.mahsulot.id}}/" class="title">{{tanlangan.mahsulot.nom}}</a>
                                        <p class="price mb-2">{{tanlangan.mahsulot.narx}}</p>
                                        <a href="/buyurtma/add_savatitem/{{tanlangan.mahsulot.id}}/"
                                           class="btn btn-secondary btn-sm"> Add to cart </a>
                                        <a href="/buyurtma/t_ochir/{{tanlangan.id}}/" class="btn btn-danger btn-sm"
                                           data-toggle="tooltip" title=""
                                           data-original-title="Remove from wishlist"> <i class="fa fa-times"></i> </a>
                                    </figcaption>
                                </figure>
                            </div> <!-- col.// -->
                        </div> <!-- row .//  -->
                            {% endfor %}

                    </div> <!-- card-body.// -->
                </article>


            </main> <!-- col.// -->
        </div>

    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


<!-- ========================= FOOTER ========================= -->
<footer class="section-footer bg-secondary">
    <div class="container">
        <section class="footer-top padding-y-lg text-white">
            <div class="row">
                <aside class="col-md col-6">
                    <h6 class="title">Brands</h6>
                    <ul class="list-unstyled">
                        <li><a href="#">Adidas</a></li>
                        <li><a href="#">Puma</a></li>
                        <li><a href="#">Reebok</a></li>
                        <li><a href="#">Nike</a></li>
                    </ul>
                </aside>
                <aside class="col-md col-6">
                    <h6 class="title">Company</h6>
                    <ul class="list-unstyled">
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Career</a></li>
                        <li><a href="#">Find a store</a></li>
                        <li><a href="#">Rules and terms</a></li>
                        <li><a href="#">Sitemap</a></li>
                    </ul>
                </aside>
                <aside class="col-md col-6">
                    <h6 class="title">Help</h6>
                    <ul class="list-unstyled">
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">Money refund</a></li>
                        <li><a href="#">Order status</a></li>
                        <li><a href="#">Shipping info</a></li>
                        <li><a href="#">Open dispute</a></li>
                    </ul>
                </aside>
                <aside class="col-md col-6">
                    <h6 class="title">Account</h6>
                    <ul class="list-unstyled">
                        <li><a href="#"> User Login </a></li>
                        <li><a href="#"> User register </a></li>
                        <li><a href="#"> Account Setting </a></li>
                        <li><a href="#"> My Orders </a></li>
                    </ul>
                </aside>
                <aside class="col-md">
                    <h6 class="title">Social</h6>
                    <ul class="list-unstyled">
                        <li><a href="#"> <i class="fab fa-facebook"></i> Facebook </a></li>
                        <li><a href="#"> <i class="fab fa-twitter"></i> Twitter </a></li>
                        <li><a href="#"> <i class="fab fa-instagram"></i> Instagram </a></li>
                        <li><a href="#"> <i class="fab fa-youtube"></i> Youtube </a></li>
                    </ul>
                </aside>
            </div> <!-- row.// -->
        </section>    <!-- footer-top.// -->

        <section class="footer-bottom text-center">

            <p class="text-white">Privacy Policy - Terms of Use - User Information Legal Enquiry Guide</p>
            <p class="text-muted"> &copy 2019 Company name, All rights reserved </p>
            <br>
        </section>
    </div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->
{% endblock %}

templates/tasdiqlash.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache"/>
    <meta http-equiv="cache-control" content="max-age=604800"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Website title - bootstrap html template</title>

    <link href="images/favicon.ico" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

    <!-- Font awesome 5 -->
    <link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css"/>

    <!-- custom javascript -->
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>

</head>
<body>

<!-- REMOVE FOLLOWING LINK -->
<a href="http://bootstrap-ecommerce.com/page-themes.html" class="btn btn-dark rounded-pill"
   style="font-size:13px; z-index:100; position: fixed; bottom:10px; right:10px;">Download theme</a>
<!-- REMOVE  //END -->


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
        <div class="card-body">
            <h4 class="card-title mb-4">SMS kod tasdiqlash</h4>
            <form method="post">
                {% csrf_token %}

                <div class="form-group">
                    <input name="kod" class="form-control" placeholder="Tasdiqlash kodi" type="text">
                </div> <!-- form-group// -->

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Tasdiqlash</button>
                </div> <!-- form-group// -->

            </form>
        </div> <!-- card-body.// -->
    </div> <!-- card .// -->
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

</body>
</html>